name: forexbot
on:
  workflow_dispatch:      # botón manual
  schedule:
    - cron: '*/5 * * * *' # cada 5 min
    - cron: '0 4 * * *'   # 04:00 UTC = 06:00 Berlín
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      BOT_TOKEN:  ${{ secrets.BOT_TOKEN }}
      CHAT_ID:    ${{ secrets.CHAT_ID }}      # debe empezar por -100…
      THREAD_ID:  ${{ secrets.THREAD_ID }}    # número del tema (o 0)
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps
        run: pip install -r requirements.txt   # ← ahora sí usa tu archivo

      # ───── PING de prueba solo cuando pulses “Run workflow” ─────
      - name: Run bot
        env:
          FORCE_TEST: ${{ github.event_name == 'workflow_dispatch' && '1' || '' }}
        run: python -u bot.py
