name: 🔔 Forex News Bot

on:
  schedule:
    # Diario a las 06:00 CET (05:00 UTC en invierno, 04:00 UTC en verano)
    - cron: '05 05 * * *'
    # Cada 5 minutos (para notificaciones 5 min antes)
    - cron: '*/5 * * * *'
    # Sábados 17:00 CET (16:00 UTC invierno, 15:00 UTC verano)
    - cron: '15 15 * * SAT'
    # Domingos 17:00 CET
    - cron: '15 15 * * SUN'
  workflow_dispatch:

jobs:
  run-forex-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-telegram-bot pytz

      - name: Run bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID:   ${{ secrets.CHAT_ID }}
          THREAD_ID: ${{ secrets.THREAD_ID }}
        run: python bot.py
