name: forexbot
on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'    # cada 5 min
    - cron: '0 4 * * *'      # diario 04:00 UTC → 06:00 Berlín
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      BOT_TOKEN:  ${{ secrets.BOT_TOKEN }}
      CHAT_ID:    ${{ secrets.CHAT_ID }}
      THREAD_ID:  ${{ secrets.THREAD_ID }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        run: python -u bot.py
