name: forexbot
on:
  workflow_dispatch:        # botón “Run workflow”
  schedule:
    - cron: '*/5 * * * *'   # cada 5 min (alertas)
    - cron: '0 4 * * *'     # 04:00 UTC = 06:00 Berlín (reporte diario)

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      BOT_TOKEN:  ${{ secrets.BOT_TOKEN }}
      CHAT_ID:    ${{ secrets.CHAT_ID }}
      THREAD_ID:  ${{ secrets.THREAD_ID }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps
        run: pip install -r requirements.txt

      # → si lo lanzas desde el botón, FORCE_TEST=1 dispara el ping
      - name: Run bot
        env:
          FORCE_TEST: ${{ github.event_name == 'workflow_dispatch' && '1' || '' }}
        run: python -u bot.py
