name: 🔔 Forex News Bot

on:
  schedule:
    - cron: '0 4 * * *'   # Todos los días a las 06:00 Berlín (04:00 UTC)
    - cron: '0 15 * * 6'  # Todos los sábados a las 17:00 Berlín (15:00 UTC)
    - cron: '0 15 * * 0'  # Todos los domingos a las 17:00 Berlín (15:00 UTC)
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID:    ${{ secrets.CHAT_ID }}
          THREAD_ID:  ${{ secrets.THREAD_ID }}
        run: python bot.py
