name: Weekly Forex News Report

on:
  schedule:
    - cron: '0 17 * * 0'  # Domingo a las 17:00 UTC
  workflow_dispatch:  # Permite correrlo manualmente también

jobs:
  send-report:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r forex-news-bot/requirements.txt

      - name: Ejecutar bot.py
        run: python forex-news-bot/bot.py
